export const example54CardDeck = [
    {
        id: 42,
        value: 4,
        name: '4',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 76,
        value: 12,
        name: 'Q',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 91,
        value: 1,
        name: 'A',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 102,
        value: 12,
        name: 'Q',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 74,
        value: 10,
        name: '10',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 15,
        value: 3,
        name: '3',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 28,
        value: 3,
        name: '3',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 94,
        value: 4,
        name: '4',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 65,
        value: 1,
        name: 'A',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 54,
        value: 3,
        name: '3',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 92,
        value: 2,
        name: '2',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 85,
        value: 8,
        name: '8',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 86,
        value: 9,
        name: '9',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 22,
        value: 10,
        name: '10',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 21,
        value: 9,
        name: '9',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 12,
        value: 13,
        name: 'K',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 49,
        value: 11,
        name: 'J',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 10,
        value: 11,
        name: 'J',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 52,
        value: 1,
        name: 'A',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 44,
        value: 6,
        name: '6',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 46,
        value: 8,
        name: '8',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 16,
        value: 4,
        name: '4',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 19,
        value: 7,
        name: '7',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 1,
        value: 2,
        name: '2',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 62,
        value: 11,
        name: 'J',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 38,
        value: 13,
        name: 'K',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 31,
        value: 6,
        name: '6',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 72,
        value: 8,
        name: '8',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 6,
        value: 7,
        name: '7',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 73,
        value: 9,
        name: '9',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 26,
        value: 1,
        name: 'A',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 45,
        value: 7,
        name: '7',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 71,
        value: 7,
        name: '7',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 87,
        value: 10,
        name: '10',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 100,
        value: 10,
        name: '10',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 13,
        value: 1,
        name: 'A',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 63,
        value: 12,
        name: 'Q',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 39,
        value: 1,
        name: 'A',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 89,
        value: 12,
        name: 'Q',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 48,
        value: 10,
        name: '10',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 64,
        value: 13,
        name: 'K',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 11,
        value: 12,
        name: 'Q',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 51,
        value: 13,
        name: 'K',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 84,
        value: 7,
        name: '7',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 93,
        value: 3,
        name: '3',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 56,
        value: 5,
        name: '5',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 77,
        value: 13,
        name: 'K',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 36,
        value: 11,
        name: 'J',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 98,
        value: 8,
        name: '8',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 18,
        value: 6,
        name: '6',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 69,
        value: 5,
        name: '5',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 7,
        value: 8,
        name: '8',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 61,
        value: 10,
        name: '10',
        suit: 'S',
        isOpen: false,
    },
    {
        id: 4,
        value: 5,
        name: '5',
        suit: 'S',
        isOpen: false,
    },
];
